"""
Multi-machine worker inventory.

Auto-generated by remote/provision.py — safe to edit manually.
"""

# fmt: off
WORKERS = [
    {"name": "a", "host": "69.143.221.78", "port": 23106 , "user": "root", "instance_id": 35602655},  # RTX PRO 6000 WS
]
# fmt: on

PROJECT_NAME = "mario"
