"""
Multi-machine worker inventory.

Auto-generated by remote/provision.py — safe to edit manually.
"""

# fmt: off
WORKERS = [
    {"name": "a", "host": "50.35.188.80", "port": 5065  , "user": "root", "instance_id": 34224081},  # RTX PRO 6000 S
]
# fmt: on

PROJECT_NAME = "mario"
