"""
Multi-machine worker inventory.

Auto-generated by remote/provision.py — safe to edit manually.
"""

# fmt: off
WORKERS = [
    {"name": "a", "host": "69.63.236.192", "port": 26777 , "user": "root", "instance_id": 34645748},  # RTX PRO 6000 S
]
# fmt: on

PROJECT_NAME = "mario"
